apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello
        shell: sh
        run: |
          echo "hello world!!"
      - uses: cloudbees-io/checkout@v1
        name: Checkout
      - uses: docker://golang:1.20.3-alpine3.17
        name: Compute version
        id: compute-version
        shell: sh
        run: |
          cat version > $CLOUDBEES_OUTPUTS/version
      - uses: training-GHA-Talavera
        name: Run remote GHA workflow
        with:
          repo-name: sample-go-app
          branch-name: main
          workflow-name: cloudbeesGHA
    outputs:
      version: ${{ steps.compute-version.outputs.version }}
  deploy:
    environment: devJT
    steps:
      - uses: docker://golang:1.20
        name: Pretend to deploy
        run: echo "Pretending to deploy version ${{ needs.build.outputs.version }} to
          namespace ${{ vars.DEPLOY_NAMESPACE }} using token ${{
          secrets.DEPLOY_TOKEN }}"
    needs:
      - build
